### ISSUE TITLE
Question about the resolution of alleles reported in  ./resources/1000G.bglv4.bgl.phased.vcf.gz

### ISSUE THREAD

**Issue by brettva** [immunogenomics/HLA-TAPAS#7]
@WansonChoi 

Is it correct that all alleles reported in the `ID` col of  `./resources/1000G.bglv4.bgl.phased.vcf.gz` we actually translated from g-group resolution data? If so did this translation occur by using the `NomenCleaner` module? (ie just the first compatible 4 field allele was reported when one g-group mapped to multiple 4 field alleles? 

Just checking my understanding, thank you!

**Comment by WansonChoi** [comment]
@brettva 

Given output of HLA-TAPAS, It's correct. all HLA alleles reported in the ID column will be G-group resolution because essentially HLA type input of HLA-TAPAS is G-group resolution data. Though HLA alleles may look 4-field nomenclature due to NomenCleaner, they are G-group resolution alleles in origin.

cf) That data is a toy example data. It's strictly not G-group resolution data.
